export const games = [
  {
    id: "pong",
    name: "Hand Pong",
    icon: "🏓",
    description: "Duel a ranked AI rival — pinch = smash, grab orbs, climb ROOKIE → NIGHTMARE.",
    requires: ["hand"],
    load: () => import("./pong/index.js"),
  },
  {
    id: "breakout",
    name: "Breakout",
    icon: "🧱",
    description: "Move your hand left/right to smash all the bricks.",
    requires: ["hand"],
    load: () => import("./breakout/index.js"),
  },
  {
    id: "snake",
    name: "Snake",
    icon: "🐍",
    description: "Steer by moving your hand away from the center.",
    requires: ["hand"],
    load: () => import("./snake/index.js"),
  },
  {
    id: "slash",
    name: "Fruit Slash",
    icon: "🍉",
    description: "Swipe fast to slice flying fruit — chain combos, don't hit the bombs.",
    requires: ["hand"],
    load: () => import("./slash/index.js"),
  },
  {
    id: "asteroids",
    name: "Asteroids",
    icon: "🚀",
    description: "Clear sector after sector — fighters, bosses, power-ups. Pinch = rapid fire · fist = bomb.",
    requires: ["hand"],
    load: () => import("./asteroids/index.js"),
  },
];
